import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//reactが動くか確認する
import React, { useState } from "react"

const Home: NextPage = () => {

  const [message, setMessage] = useState("");

  const handle = () => {
    console.log(message);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>test</h1>
        <input type="text" placeholder="名前" onChange={(e)=>{setMessage(e.target.value)} }/>
        <button onClick={handle}>consoleを見る</button>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
