import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React, { useState } from "react"
import { Button, Container, Stack, TextField } from '@mui/material'
// import { fetchGet, fetchPost } from '../utils/api-helpers'
import axios from "axios"

const Home: NextPage = () => {

  const [message, setMessage] = useState("");

  const handle = async() => (
    axios.get(
      process.env.NEXT_PUBLIC_API_BASE + "/helthCheck"
    )
    .then(res => {
      console.log(res);
    })
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>test</h1>
        <input type="text" placeholder="名前" onChange={(e)=>{setMessage(e.target.value)} }/>
        <button onClick={handle}>consoleを見る</button>
        {/* <Handle /> */}

        <Container maxWidth="sm" sx={{ pt: 5 }}>
          <Stack spacing={3}>
            <TextField
              required
              label="アドレス"
            />
          </Stack>
        </Container>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
