import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React, { useState } from "react"
import { Button, Container, Stack, TextField } from '@mui/material'
// import { fetchGet, fetchPost } from '../utils/api-helpers'
import axios from "axios"
import { SubmitHandler, useForm } from 'react-hook-form'

interface NftForm {
  to: string
  name: string
  image: string
  description: string
  price: string
  seller: string
}

const Home: NextPage = () => {
  const { register, handleSubmit } = useForm<NftForm>()

  const submit: SubmitHandler<NftForm> = (data) => {
    
    axios.post(
      process.env.NEXT_PUBLIC_API_BASE + "/mint",
      data
    )
    .then(res => {
      console.log(res);
      console.log(data);
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>MINT YOUR NFT!</h1>

        <Container maxWidth="sm" sx={{ pt: 5 }}>
          <Stack spacing={3}>
            <TextField
              required
              label="アドレス"
              {...register('to')}
            />
            <TextField
              required
              label="作品名"
              {...register('name')}
            />
            <TextField
              required
              label="画像URL(ipfs)"
              {...register('image')}
            />
            <TextField
              required
              label="作品概要"
              {...register('description')}
            />
            <TextField
              required
              label="値段"
              {...register('price')}
            />
            <TextField
              required
              label="販売者アドレス"
              {...register('seller')}
            />
            <Button
              color="primary"
              variant="contained"
              size="large"
              onClick={handleSubmit(submit)}
            >
              NFTを作成する
            </Button>
          </Stack>
        </Container>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
